# Generated by Django 3.1.5 on 2021-01-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=254)),
                ('image', models.ImageField(upload_to='media/')),
                ('event_description', models.TextField()),
                ('event_dates', models.CharField(max_length=254)),
                ('event_buy_button_text', models.CharField(max_length=254)),
                ('event_display_status', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=10)),
                ('event_instructions', models.CharField(max_length=254)),
            ],
        ),
    ]
