# Generated by Django 3.1.5 on 2021-01-28 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_events_create_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='event_buy_button_text',
            new_name='event_price',
        ),
    ]
