# Generated by Django 3.1.5 on 2021-01-29 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20210128_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
