# Generated by Django 3.1.5 on 2021-02-02 11:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20210129_1842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='event_price',
            new_name='event_ticket_price',
        ),
        migrations.AddField(
            model_name='events',
            name='event_ticket_quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
