# Generated by Django 3.1.5 on 2021-02-02 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_events_event_ticket_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='event_ticket_quantity',
        ),
    ]
