# Generated by Django 3.1.5 on 2021-02-02 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20210202_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='event_ticket_price',
            new_name='event_price',
        ),
    ]
