# Generated by Django 3.1.5 on 2021-02-12 22:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_eventdates'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdates',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.events'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='event_remaining_ticket',
            field=models.IntegerField(default=0),
        ),
    ]
