# Generated by Django 3.1.5 on 2021-02-12 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_auto_20210212_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='event_dates',
        ),
    ]
