# Generated by Django 3.1.5 on 2021-03-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_remove_events_event_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdates',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
