# Generated by Django 3.1.5 on 2021-04-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_auto_20210323_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='is_free_event',
            field=models.BooleanField(default=False),
        ),
    ]
