# Generated by Django 3.1.5 on 2021-04-20 10:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_bookingfreeevents'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingfreeevents',
            name='event_booking_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
