# Generated by Django 3.1.5 on 2021-04-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_bookingfreeevents_event_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingfreeevents',
            name='event_booking_date',
            field=models.CharField(max_length=50),
        ),
    ]
