# Generated by Django 3.1.5 on 2021-04-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_auto_20210420_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='event_remaining_ticket',
        ),
        migrations.RemoveField(
            model_name='events',
            name='event_ticket_quantity',
        ),
        migrations.AddField(
            model_name='eventdates',
            name='available_ticket',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventdates',
            name='total_tickets',
            field=models.IntegerField(default=1),
        ),
    ]
