# Generated by Django 3.1.5 on 2021-04-20 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_auto_20210420_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventdates',
            old_name='available_ticket',
            new_name='ticket_sold',
        ),
    ]
