# Generated by Django 3.1.5 on 2021-04-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_auto_20210420_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdates',
            name='available_tickets',
            field=models.IntegerField(default=0),
        ),
    ]
