# Generated by Django 3.1.5 on 2021-04-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('admin_email', models.EmailField(max_length=50)),
                ('message', models.TextField()),
                ('receieve_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
