# Generated by Django 3.1.5 on 2021-04-24 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus_and_aboutus', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment',
            new_name='Contactus',
        ),
    ]
