# Generated by Django 3.1.5 on 2021-04-24 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus_and_aboutus', '0002_auto_20210424_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='admin_email',
        ),
    ]
