# Generated by Django 3.1.5 on 2021-04-25 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus_and_aboutus', '0006_auto_20210425_0752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='title',
            new_name='ministy',
        ),
    ]
