# Generated by Django 3.1.5 on 2021-02-02 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20210202_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='country',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='county',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_total_amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='street_address1',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='street_address2',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='town_or_city',
        ),
    ]
