# Generated by Django 3.1.5 on 2021-02-02 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20210202_1331'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentLineItem',
        ),
    ]
