# Generated by Django 3.1.5 on 2021-02-02 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20210202_1314'),
        ('payment', '0004_delete_paymentlineitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_ticket_qty', models.IntegerField(default=0)),
                ('lineitem_total', models.DecimalField(decimal_places=2, editable=False, max_digits=6)),
                ('event_ticket_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.events')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineitems', to='payment.payment')),
            ],
        ),
    ]
