# Generated by Django 3.1.5 on 2021-02-02 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_paymentlineitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentlineitem',
            old_name='event_ticket_price',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='paymentlineitem',
            old_name='lineitem_total',
            new_name='payment_total',
        ),
        migrations.AlterField(
            model_name='paymentlineitem',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_total', to='payment.payment'),
        ),
    ]
