# Generated by Django 3.1.5 on 2021-02-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_auto_20210202_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlineitem',
            name='payment_total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=6),
        ),
    ]
