# Generated by Django 3.1.5 on 2021-02-03 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_auto_20210203_0953'),
        ('payment', '0009_delete_paymentlineitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_amount',
            new_name='donation_payment_amount',
        ),
        migrations.AddField(
            model_name='payment',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.events'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='event_ticket_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.CreateModel(
            name='PaymentLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_ticket_qty', models.IntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.events')),
            ],
        ),
    ]
