# Generated by Django 3.1.5 on 2021-02-03 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_auto_20210203_0953'),
        ('payment', '0010_auto_20210203_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.events'),
        ),
    ]
