# Generated by Django 3.1.5 on 2021-02-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_auto_20210203_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='event_ticket_qty',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='PaymentLineItem',
        ),
    ]
