# Generated by Django 3.1.5 on 2021-02-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_auto_20210206_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
