# Generated by Django 3.1.5 on 2021-02-07 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0015_auto_20210207_1030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketspayment',
            old_name='payment_total',
            new_name='lineitem_total',
        ),
    ]
