# Generated by Django 3.1.5 on 2021-02-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0016_auto_20210207_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
