# Generated by Django 3.1.5 on 2021-02-08 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_eventdates'),
        ('payment', '0022_auto_20210207_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketspayment',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.events'),
            preserve_default=False,
        ),
    ]
