# Generated by Django 3.1.5 on 2021-03-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0024_auto_20210322_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketspayment',
            name='event_date',
            field=models.DateTimeField(),
        ),
    ]
