# Generated by Django 3.1.5 on 2021-03-23 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0025_auto_20210323_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketspayment',
            name='event_date',
            field=models.CharField(max_length=150),
        ),
    ]
