# Generated by Django 3.1.5 on 2021-05-10 10:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0026_auto_20210323_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
