# Generated by Django 3.1.5 on 2021-01-14 13:35

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('video', embed_video.fields.EmbedVideoField()),
                ('about', models.TextField(max_length=200)),
                ('date', models.DateTimeField()),
                ('status', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=10)),
            ],
        ),
    ]
