# Generated by Django 3.1.5 on 2021-01-14 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20210114_1358'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Videos',
            new_name='Item',
        ),
    ]
