# Generated by Django 3.1.5 on 2021-01-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20210114_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='video',
            field=models.URLField(),
        ),
    ]
