# Generated by Django 3.1.5 on 2021-03-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20210114_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='SundayServiceInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('preacher_name', models.CharField(max_length=50)),
                ('sermon_title', models.CharField(max_length=100)),
                ('bible_refrence', models.TextField(blank=True)),
                ('worship_hymm1', models.CharField(max_length=100)),
                ('worship_hymm2', models.CharField(max_length=100)),
                ('worship_hymm3', models.CharField(max_length=100)),
                ('worship_hymm4', models.CharField(max_length=100)),
                ('important_notices', models.CharField(max_length=300)),
                ('date', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
