# Generated by Django 3.1.5 on 2021-03-29 14:27

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_videos_video_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sundayserviceinformation',
            name='available_bookings',
            field=models.IntegerField(default=50),
        ),
        migrations.CreateModel(
            name='SundayServiceBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('number_of_bookings', models.IntegerField(default=1)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('service_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.sundayserviceinformation')),
            ],
        ),
    ]
