# Generated by Django 3.1.5 on 2021-04-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_auto_20210428_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sundayserviceinformation',
            name='important_notices',
            field=models.CharField(default='Notices', max_length=300),
        ),
        migrations.AlterField(
            model_name='sundayserviceinformation',
            name='preacher_name',
            field=models.CharField(default='Preacher Name', max_length=50),
        ),
        migrations.AlterField(
            model_name='sundayserviceinformation',
            name='sermon_title',
            field=models.CharField(default='Sermon title', max_length=100),
        ),
        migrations.AlterField(
            model_name='sundayserviceinformation',
            name='title',
            field=models.CharField(default='Service title', max_length=50),
        ),
        migrations.AlterField(
            model_name='sundayserviceinformation',
            name='worship_hymm1',
            field=models.CharField(default='Hymm 1', max_length=100),
        ),
        migrations.AlterField(
            model_name='sundayserviceinformation',
            name='worship_hymm2',
            field=models.CharField(default='Hymm 2', max_length=100),
        ),
        migrations.AlterField(
            model_name='sundayserviceinformation',
            name='worship_hymm3',
            field=models.CharField(default='Hymm 3', max_length=100),
        ),
        migrations.AlterField(
            model_name='sundayserviceinformation',
            name='worship_hymm4',
            field=models.CharField(default='Hymm 4', max_length=100),
        ),
    ]
