# Generated by Django 3.1.5 on 2021-01-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministries', '0002_auto_20210115_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alphagroup',
            name='message',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
