# Generated by Django 3.1.5 on 2021-01-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministries', '0003_auto_20210115_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupHeadings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_heading', models.CharField(max_length=25)),
                ('sub_title_heading', models.CharField(max_length=25)),
                ('bible_verse', models.TextField(max_length=150)),
                ('group_promotion', models.TextField(max_length=100)),
                ('group_leader', models.CharField(max_length=20)),
                ('group_leader_email', models.EmailField(blank=True, max_length=50)),
                ('group_leader_info', models.TextField(max_length=80)),
                ('important_information', models.TextField(max_length=100)),
            ],
        ),
    ]
