# Generated by Django 3.1.5 on 2021-01-16 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ministries', '0004_groupheadings'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingTimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.CharField(max_length=25)),
                ('group_lead_by', models.CharField(max_length=25)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='groupheadings',
            name='meeting_times',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ministries.meetingtimes'),
        ),
    ]
