# Generated by Django 3.1.5 on 2021-01-16 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ministries', '0006_auto_20210116_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupheadings',
            name='meeting_times',
        ),
        migrations.AddField(
            model_name='meetingtimes',
            name='meeting_times',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ministries.groupheadings'),
        ),
        migrations.AlterField(
            model_name='groupheadings',
            name='bible_verse',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='groupheadings',
            name='group_leader_info',
            field=models.TextField(max_length=350),
        ),
        migrations.AlterField(
            model_name='groupheadings',
            name='important_information',
            field=models.TextField(max_length=350),
        ),
    ]
