# Generated by Django 3.1.5 on 2021-01-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministries', '0007_auto_20210116_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingtimes',
            name='date',
            field=models.TimeField(),
        ),
    ]
