# Generated by Django 3.1.5 on 2021-01-16 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ministries', '0008_auto_20210116_1301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetingtimes',
            old_name='date',
            new_name='time',
        ),
    ]
