# Generated by Django 3.1.5 on 2021-01-16 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ministries', '0009_auto_20210116_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupheadings',
            old_name='title_heading',
            new_name='ministry_heading',
        ),
    ]
