# Generated by Django 3.1.5 on 2021-01-16 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ministries', '0010_auto_20210116_1309'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupHeadings',
            new_name='Ministries',
        ),
    ]
