# Generated by Django 3.1.5 on 2021-01-16 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ministries', '0011_auto_20210116_1311'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AlphaGroup',
            new_name='Message',
        ),
    ]
