# Generated by Django 3.1.5 on 2021-01-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministries', '0013_auto_20210116_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ministries',
            name='group_promotion',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='ministries',
            name='ministry_heading',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
