# Generated by Django 3.1.5 on 2021-01-17 10:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ministries', '0014_auto_20210116_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingtimes',
            name='time',
        ),
        migrations.AddField(
            model_name='meetingtimes',
            name='timings',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
