# Generated by Django 3.1.5 on 2021-01-18 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ministries', '0016_weekdays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingtimes',
            name='week_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ministries.weekdays'),
        ),
    ]
