# Generated by Django 3.1.5 on 2021-01-18 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ministries', '0018_auto_20210118_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingtimes',
            name='meeting_times',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ministries.weekdays'),
        ),
    ]
