# Generated by Django 3.1.5 on 2021-01-18 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ministries', '0019_auto_20210118_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingtimes',
            name='meeting_ministry_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ministries.ministries'),
        ),
    ]
