# Generated by Django 3.1.5 on 2021-01-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministries', '0021_auto_20210118_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetingtimes',
            old_name='meeting_times',
            new_name='meeting_day',
        ),
        migrations.AlterField(
            model_name='meetingtimes',
            name='week_day',
            field=models.CharField(max_length=30),
        ),
    ]
