# Generated by Django 3.1.5 on 2021-01-18 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ministries', '0022_auto_20210118_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingtimes',
            name='week_day',
        ),
    ]
