# Generated by Django 3.1.5 on 2021-04-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministries', '0023_remove_meetingtimes_week_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='postcode',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
