# Generated by Django 3.1.5 on 2021-03-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'verbose_name_plural': 'Notices'},
        ),
        migrations.RenameField(
            model_name='notice',
            old_name='date',
            new_name='date_time',
        ),
        migrations.AlterField(
            model_name='notice',
            name='notice_title',
            field=models.CharField(max_length=100),
        ),
    ]
