# Generated by Django 3.1.5 on 2021-03-24 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0002_auto_20210324_1252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='notice_give_by',
            new_name='notice_given_by',
        ),
    ]
