# Generated by Django 3.1.5 on 2021-04-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0004_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='upload',
            field=models.FileField(upload_to='../uploads/newsletters/'),
        ),
    ]
