# Generated by Django 3.1.5 on 2021-04-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0005_auto_20210426_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='upload',
            field=models.FileField(upload_to='uploads/newsletters/'),
        ),
    ]
