# Generated by Django 3.1.5 on 2021-01-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteColorTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_name', models.CharField(max_length=20)),
                ('primary_color_code', models.CharField(blank=True, max_length=10, null='True')),
                ('secondary_color_code', models.CharField(blank=True, max_length=10, null='True')),
            ],
            options={
                'verbose_name_plural': 'Colors',
            },
        ),
    ]
