# Generated by Django 3.1.5 on 2021-01-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_currentcolortheme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitecolortheme',
            old_name='primary_color_code',
            new_name='primary_background_color_code',
        ),
        migrations.RenameField(
            model_name='sitecolortheme',
            old_name='secondary_color_code',
            new_name='primary_foreground_color_code',
        ),
        migrations.AddField(
            model_name='sitecolortheme',
            name='secondary_background_color_code',
            field=models.CharField(blank=True, max_length=10, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='sitecolortheme',
            name='secondary_foreground_color_code',
            field=models.CharField(blank=True, max_length=10, null='True'),
            preserve_default='True',
        ),
    ]
