# Generated by Django 3.1.5 on 2021-01-10 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_herosectiontext'),
    ]

    operations = [
        migrations.RenameField(
            model_name='herosectiontext',
            old_name='description',
            new_name='hero_heading',
        ),
    ]
