# Generated by Django 3.1.5 on 2021-01-10 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210110_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosectiontext',
            name='hero_heading',
            field=models.CharField(max_length=200),
        ),
    ]
