# Generated by Django 3.1.5 on 2021-01-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210110_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarousleSectionText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=20)),
                ('paragraph', models.CharField(max_length=200)),
            ],
        ),
    ]
