# Generated by Django 3.1.5 on 2021-01-11 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_carouslesectiontext'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarousleSectionText',
            new_name='CarouselSectionText',
        ),
    ]
