# Generated by Django 3.1.5 on 2021-01-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210111_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselInner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel_image', models.ImageField(upload_to='media/')),
                ('heading', models.CharField(max_length=20)),
                ('paragraph', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='carouselsectiontext',
            name='paragraph',
            field=models.CharField(max_length=140),
        ),
    ]
