# Generated by Django 3.1.5 on 2021-01-11 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210111_1234'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarouselInner',
            new_name='CarouselInnerSection',
        ),
    ]
