# Generated by Django 3.1.5 on 2021-01-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_secondparallaxsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondparallaxsection',
            name='main_paragraph',
            field=models.TextField(max_length=250),
        ),
    ]
