# Generated by Django 3.1.5 on 2021-01-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20210113_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselinnersection',
            name='paragraph',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='carouselsectiontext',
            name='paragraph',
            field=models.TextField(max_length=140),
        ),
        migrations.AlterField(
            model_name='herosectiontext',
            name='hero_heading',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='secondparallaxsection',
            name='instruction_paragraph',
            field=models.TextField(max_length=65),
        ),
    ]
