# Generated by Django 3.1.5 on 2021-01-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20210113_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyGroupText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=20)),
                ('paragraph', models.TextField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='secondparallaxsection',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
