# Generated by Django 3.1.5 on 2021-04-17 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ministries', '0023_remove_meetingtimes_week_day'),
        ('home', '0015_carouselsectiontext_ministry'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondparallaxsection',
            name='ministry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ministries.ministries'),
        ),
    ]
