# Generated by Django 3.1.5 on 2021-04-17 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_auto_20210329_1427'),
        ('home', '0016_secondparallaxsection_ministry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secondparallaxsection',
            name='ministry',
        ),
        migrations.AddField(
            model_name='secondparallaxsection',
            name='sunday_services',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.sundayserviceinformation'),
        ),
    ]
